server:
  port: 8080

spring:
  datasource:
    username: admin
    password: RameshRamesh
    url: jdbc:mysql://ramesh.cza0owzvgmgd.ap-south-1.rds.amazonaws.com:3306/Reddy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
